// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqkLr7C0p6r2rMHIes655-WPgYq-5MDXM',
    appId: '1:407248065183:web:8c2c54be7fa71a2fd5c8aa',
    messagingSenderId: '407248065183',
    projectId: 'sanber-mobdev',
    authDomain: 'sanber-mobdev.firebaseapp.com',
    storageBucket: 'sanber-mobdev.firebasestorage.app',
    measurementId: 'G-38K41MKT5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7QnBAsn1gtf0OXMqzJRl-6FLt3pLEnlY',
    appId: '1:407248065183:android:f38a14de8a6654e6d5c8aa',
    messagingSenderId: '407248065183',
    projectId: 'sanber-mobdev',
    storageBucket: 'sanber-mobdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4DhI7COTYbjrQhJU2782HsVMuNpsCoo',
    appId: '1:407248065183:ios:1c425ac2d1b3b69cd5c8aa',
    messagingSenderId: '407248065183',
    projectId: 'sanber-mobdev',
    storageBucket: 'sanber-mobdev.firebasestorage.app',
    iosBundleId: 'com.example.tugas12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4DhI7COTYbjrQhJU2782HsVMuNpsCoo',
    appId: '1:407248065183:ios:1c425ac2d1b3b69cd5c8aa',
    messagingSenderId: '407248065183',
    projectId: 'sanber-mobdev',
    storageBucket: 'sanber-mobdev.firebasestorage.app',
    iosBundleId: 'com.example.tugas12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqkLr7C0p6r2rMHIes655-WPgYq-5MDXM',
    appId: '1:407248065183:web:dcba14338aa4cb99d5c8aa',
    messagingSenderId: '407248065183',
    projectId: 'sanber-mobdev',
    authDomain: 'sanber-mobdev.firebaseapp.com',
    storageBucket: 'sanber-mobdev.firebasestorage.app',
    measurementId: 'G-2W7JCR504K',
  );
}
