name: finalproject_flutterapp2
description: "Final Project Flutter App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.6
  firebase_auth: ^5.4.1
  shared_preferences: ^2.5.1
  dio: ^5.8.0+1
  json: ^0.20.4
  url_launcher: ^6.3.1
  firebase_core: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.9.2
  flutter_lints: ^5.0.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/app_main_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\icon\app_main_icon.png
    - assets\icon\homescreen_keanggotaan.png
    - assets\icon\homescreen_kegiatan.png
    - assets\icon\homescreen_pedoman.png
    - assets\icon\homescreen_forum.png
    - assets\icon\homescreen_survei.png
    - assets\icon\homescreen_download.png
    - assets\icon\homescreen_kontak.png
    - assets\icon\homescreen_().png
    - assets\image\detailpage_image1.png
    - assets\image\detailpage_image2.png
    - assets\image\profile_pic.jpg

    - assets\icon\aboutme_telegram.png
    - assets\icon\aboutme_sanbercode.png
    - assets\icon\aboutme_pythonpng.png
    - assets\icon\aboutme_linkedin.png
    - assets\icon\aboutme_flutter.png
    - assets\icon\aboutme_email.png
    - assets\icon\aboutme_kotlin.png

    - assets\image\homescreen_image1.png
    - assets\image\homescreen_berita_image1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
