name: finalproject_flutterapp2
description: "Final Project Flutter App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.6
  firebase_auth: ^5.4.1
  shared_preferences: ^2.5.1
  dio: ^5.8.0+1
  json: ^0.20.4
  url_launcher: ^6.3.1
  firebase_core: ^3.10.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_main_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets\icon\app_main_icon.png
    - assets\icon\homescreen_keanggotaan.png
    - assets\icon\homescreen_kegiatan.png
    - assets\icon\homescreen_pedoman.png
    - assets\icon\homescreen_forum.png
    - assets\icon\homescreen_survei.png
    - assets\icon\homescreen_download.png
    - assets\icon\homescreen_kontak.png
    - assets\icon\homescreen_().png
    - assets\image\detailpage_image1.png
    - assets\image\detailpage_image2.png
    - assets\image\profile_pic.jpg
    - assets/icon/icon_google.png

    - assets\icon\aboutme_telegram.png
    - assets\icon\aboutme_sanbercode.png
    - assets\icon\aboutme_pythonpng.png
    - assets\icon\aboutme_linkedin.png
    - assets\icon\aboutme_flutter.png
    - assets\icon\aboutme_email.png
    - assets\icon\aboutme_kotlin.png

    - assets\image\homescreen_image1.png
    - assets\image\homescreen_berita_image1.png
